name: Build

on:
  push:
    paths-ignore:
      - '.{gitignore,gitattributes}'
      - '.travis.yml'
  pull_request:
    paths-ignore:
      - '.{gitignore,gitattributes}'
      - '.travis.yml'

jobs:
  build-windows:
    name: Windows build
    runs-on: windows-2019

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Build
        run: msbuild.exe cli/maxcso.sln -m -p:Configuration=Release -p:Platform=x64 -p:TrackFileAccess=false

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: maxcso-windows-nonpgo
          path: maxcso.exe
          
  build-macOS:
    name: macOS ${{ matrix.suffix }} build
    strategy:
      matrix:
        include:
            - runner: macos-latest
              suffix: arm64
            - runner: macos-13
              suffix: x86
    runs-on: ${{ matrix.runner}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build
        run: |
          make -j$(sysctl -n hw.ncpu)
          tar cv maxcso | gzip -9 > maxcso-macos-${{ matrix.suffix }}.tar.gz

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: maxcso-macos-${{ matrix.suffix }}
          path: maxcso-macos-${{ matrix.suffix }}.tar.gz

  build-ubuntu:
    name: Ubuntu build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup dependencies
        run: sudo apt-get install libuv1-dev liblz4-dev

      - name: Build
        run: |
          make -j2
          tar cv maxcso | gzip -9 > maxcso-linux.tar.gz

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: maxcso-linux
          path: maxcso-linux.tar.gz
